modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "firetorch"
version = "${version}"
displayName = "VisorFireTorch"
authors = "Ninix"
displayTest = "NONE"
description = '''
The FireTorch Addon for Visor

'''

[[dependencies.firetorch]]
modId = "visor"
mandatory = true
versionRange = "[0.2.0-alpha,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.firetorch]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.firetorch]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "AFTER"
side = "BOTH"
